DROP DATABASE IF EXISTS UNIVERSIDADE;
CREATE DATABASE UNIVERSIDADE;
USE UNIVERSIDADE;

CREATE TABLE DEPARTAMENTO (
    CODIGO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255),
    NUMERO_SALA INT,
    TELEFONE_SALA VARCHAR(9),
    PRIMARY KEY (CODIGO)
);

CREATE TABLE ALUNO (
    NUMERO_MATRICULA INT NOT NULL AUTO_INCREMENT,
    CODIGO_DEPARTAMENTO_PRINCIPAL INT,
    CODIGO_DEPARTAMENTO_SECUNDARIO INT,
    NOME VARCHAR(255),
    CPF VARCHAR(11),
    ENDERECO VARCHAR(255),
    TELEFONE VARCHAR(9),
    DATA_NASCIMENTO DATE,
    SEXO CHAR,
    TURMA VARCHAR(255),
    PROGRAMA VARCHAR(255),
    PRIMARY KEY (NUMERO_MATRICULA),
    FOREIGN KEY (CODIGO_DEPARTAMENTO_PRINCIPAL)
        REFERENCES DEPARTAMENTO (CODIGO)
);

CREATE TABLE CURSO (
    CODIGO INT NOT NULL AUTO_INCREMENT,
    COD_DEPARTAMENTO_REPONSAVEL INT,
    NOME VARCHAR(255),
    DESCRICAO VARCHAR(255),
    HORAS_SEMESTRAIS INT,
    NIVEL INT,
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (COD_DEPARTAMENTO_REPONSAVEL)
        REFERENCES DEPARTAMENTO (CODIGO)
);

CREATE TABLE DISCIPLINA (
    CODIGO INT NOT NULL AUTO_INCREMENT,
    CODIGO_CURSO INT,
    NOME_PROFESSOR VARCHAR(255),
    SEMESTRE INT,
    ANO INT,
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (CODIGO_CURSO)
        REFERENCES CURSO (CODIGO)
);

CREATE TABLE HISTORICO (
    CODIGO INT NOT NULL AUTO_INCREMENT,
    CODIGO_ALUNO INT,
    CODIGO_DISCIPLINA INT,
    CONCEITO CHAR,
    NOTA DOUBLE,
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (CODIGO_ALUNO)
        REFERENCES ALUNO (NUMERO_MATRICULA),
    FOREIGN KEY (CODIGO_DISCIPLINA)
        REFERENCES DISCIPLINA (CODIGO)
);